### ISSUE TITLE
Mechanism to renew

### ISSUE THREAD

**Issue by funkypenguin** [mkuron/letsencrypt-mac#1]
This worked brilliantly, thank you.

Is there any mechanism to renew certs?

Thanks,
D

**Comment by mkuron** [comment]
Just run it again. If a certificate is within 30 days of expiration, it will be renewed.

**Comment by etcook** [comment]
Great job! Any reason not to put this on a cron?

**Comment by mkuron** [comment]
I haven't been running it from a cron job yet because letsencrypt was still a bit of a moving taget when I initially wrote this. I simply run the script manually every 2 months. The past two renewals didn't require any modifications anymore, so I think letsencrypt and letsencrypt.sh have sufficiently converged for automatic use.
So go ahead and add the script as a daily cron job (or probably better: launchd job). You can create a pull request once you've created an appropriate launchd plist.
