### ISSUE TITLE
SAN Support?

### ISSUE THREAD

**Issue by Tazintosh** [mkuron/letsencrypt-mac#4]
Hi Michael,

Quick question: does the actual script support multiple subdomain configuration or wildcard for a same certificate? I guess it's SAN?

All the best.

**Comment by mkuron** [comment]
One certificate is obtained for each custom site configured in Server.app. If that site has multiple server aliases defined, a multi-SAN certificate is obtained.

Wildcards are not supported by Let's Encrypt.

**Comment by Tazintosh** [comment]
Thanks Michael.
Indeed. On my setup, I had the following result:

• subdomain.mydomain.com --> 1 certificate generated
• subdomain2.mydomain.com --> another 1 certificate generated
• and so forth

But I also have the following case:
• 1 domain set with 2 additional domains defined (not aliases) --> 1 certificate generated for all.

**Comment by mkuron** [comment]
What's the difference between "additional domain" and "alias" to you? What Apple hides behind the "Edit..." button next to "Additional Domains" corresponds to `ServerAlias` parameters in the Apache config and `serverAlias` values in the command-line `serveradmin` tool. So to me, when I say aliases, I mean additional domains that refer to the same web site. So the behavior see is intentional. You can only specify one certificate per site, so all additional domains of that site need to be SANs in that certificate.

**Comment by Tazintosh** [comment]
Ok great.
We just have to wait for the wildcard to be supported starting January 2018 to get even more freedom
