### ISSUE TITLE
Dehydrated LICENSE value is incorrect

### ISSUE THREAD

**Issue by zenspider** [mkuron/letsencrypt-mac#6]
I had to manually patch dehydrated:

```diff
--- a/dehydrated
+++ b/dehydrated
@@ -105,7 +105,7 @@ load_config() {
 
   # Default values
   CA="https://acme-v01.api.letsencrypt.org/directory"
-  LICENSE="https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf"
+  LICENSE="https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf"
   CERTDIR=
   ACCOUNTDIR=
   CHALLENGETYPE="http-01"
```

Looks like I can't send this upstream because they've changed quite a bit since their last tagged release.

**Comment by mkuron** [comment]
This was already fixed in dehydrated 0.4.0 (https://github.com/lukas2511/dehydrated/commit/6a32f20e004b9d835cd02de9d78300be02784cf1#diff-f8a3fd80bfeb8e8456d63862cb71da83). I've switched from version 0.3.1 to 0.6.2 a month ago, so this is not an issue anymore if you update to the latest version of my repository.
